### ISSUE TITLE
couldnot install due to Failed to execute script 'Easy m3u playlist creator' due to unhandled exceptions: couldn't open

### ISSUE THREAD

**Issue by coolrose78** [imrsaleh/Easy-M3U-Playlist-Creator#1]
Failed to execute script 'Easy m3u playlist creator' due to unhandled exceptions: couldn't open "C:/icon.png" : no such file or directory

Traceback (most recent call last):
  File "Easy M3U Playlist Creator.py", line 91, in <module>
  File "tkinter\__init__.py", line 4126, in __init__
  File "tkinter\__init__.py", line 4073, in __init__
_tkinter.TclError: couldn't open "C:/icon.png": no such file or directory

**Comment by liuhui19994** [comment]
Traceback (most recent call last):
  File "Easy M3U Playlist Creator.py", line 91, in <module>
  File "tkinter\__init__.py", line 4126, in __init__
  File "tkinter\__init__.py", line 4073, in __init__
_tkinter.TclError: couldn't open "C:/icon.png": no such file or directory

**Comment by imrsaleh** [comment]
The bug has been fixed. You can try the new version now
